export let usersArray: string[] = [];
export const app = document.getElementById('app') as HTMLDivElement;
export const listUsers = document.getElementById('list_of_names') as HTMLDivElement;
export const inputNewUser = document.getElementById('name') as HTMLInputElement;
export const btnAddUser = document.getElementById('btn-add-user') as HTMLButtonElement;
export const coinsSection = document.getElementById('coin') as HTMLDivElement;
export const btnPlay = document.getElementById('play') as HTMLButtonElement;
export const messageContainer = document.getElementById('messageContainer') as HTMLDivElement;
export const animationCoin = document.getElementsByClassName('circle');
export const colorsBackground: string[] = ["#FDFCB6", "#FFC6FF", "#CAFCBF", "#FFD6A5", "#A0A0A0", "#BCB2FF"];
/*export const btnDeleteUser = document.querySelectorAll('.fas-trash-alt');*/ 
